apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagger
spec:
  template:
    spec:
      containers:
        - name: flagger
          args:
            - -mesh-provider=kubernetes
            - -metrics-server=http://flagger-prometheus:9090
            - -slack-user=shapirov
            - -slack-channel=eks-cd
            - -slack-url=https://hooks.slack.com/services/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
~
~
